"""add composite indexes user_date on metrics and activities

Revision ID: 6b5a7fffbd46
Revises: ec2914074d46
Create Date: 2026-05-16 11:24:09.455711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5a7fffbd46'
down_revision: Union[str, Sequence[str], None] = 'ec2914074d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_activities_user_date', 'activities', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    op.create_index('ix_daily_metrics_user_date', 'daily_metrics', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_daily_metrics_user_id'), 'daily_metrics', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_metrics_user_id'), table_name='daily_metrics')
    op.drop_index('ix_daily_metrics_user_date', table_name='daily_metrics')
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index('ix_activities_user_date', table_name='activities')
    # ### end Alembic commands ###
