"""add garmin_device_model to users

Revision ID: f6d8bcf495df
Revises: 0fda66f12673
Create Date: 2026-05-15 19:46:40.058887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d8bcf495df'
down_revision: Union[str, Sequence[str], None] = '0fda66f12673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('garmin_device_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'garmin_device_model')
    # ### end Alembic commands ###
